# force run: 1
dist: xenial
language: c
compiler:
  - clang
  - gcc
python:
  - "3.6"
sudo: required
before_install:
    - sudo -H DEBIAN_FRONTEND=noninteractive apt-get update
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - which python
    - python --version
#    - sudo -H PATH="${PATH}:/usr/local/clang-3.4/bin" pip3 install -r requirements.txt
    - pip3 install --user cpp-coveralls
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - stage: Unit Tests
      env: COVERALLS_PARALLEL=true
      install: ./install_unit_tests_dependencies
      script: sh -x ./scripts/do-test.sh
      after_success:
        - for f in `make -f tests/Makefile list_tests`;
          do
            cat tests/${f}.log;
          done
        - if [ "${CC}" = "gcc" -a "${BUILD_TYPE}" = "do-test" ];
          then
            sh -x ./scripts/submit-coverage.sh ;
          fi
      notifications:
        webhooks: https://coveralls.io/webhook
    - stage: Deploy Documentation
      name: Deploy Documentation to the web site repo
      script: sh -x ./scripts/do-docdeploy.sh
