# force run: 1
dist: xenial
language: c
compiler:
  - clang
  - gcc
python:
  - "3.6"
sudo: required
before_install:
    - sudo -H DEBIAN_FRONTEND=noninteractive apt-get update
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - which python
    - python --version
#    - sudo -H PATH="${PATH}:/usr/local/clang-3.4/bin" pip3 install -r requirements.txt
    - pip3 install --user cpp-coveralls
env:
  global:
    - COVERALLS_PARALLEL=true
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "ocrcwCLSoR8gvVuH3Qk4hc8y4m9gN896jiakrET1Xn9RjO4+rb35ik4Vv5uaYCKWvSEwztln0rUaPpLzNgLfLHO9BAupnSE4JTPRiCh5Ms0+QXi0DoIhiRdWJt52GngFPRGZWuKZD+wQlf4EQBXJusTI5UXXZJEbkphMIzB6z5k7zJDV5ArwYrhXkeJKgLuJymx6bV/M2FxcCFf0migEg0fxrcyjTqtM+P0KxSq6rgtEwI24YibEbG6AZrU+d9pNbDby7qp+AKdpny8qkwlSy4Otd9soLSIWz7M6vKq1fiqrb+NkNCb8uMKV7DR9qwSy6Vf66JeeyMnBKvj1NDCUpiQcQSI0xYtLcv3SBwZAaWGvxP2/DwEdVq23T55LfQume1C+ORFhFh1OUELkV+3vypG2j/TK07DVvuZAbrnxu1PwDT8KGj9nR5HoOS6m08vwidp/uajM/gxkGQpC2itXFf5ZSxW2Ibp4b6p3g3nV52jQlrVfd6WvgITfnTzj6Zc72z2KHFMTlgarv0KV8o4JbCqRq+WfZr/kh06cR+D4336nI/3ewBllHvPeDYy6qOT7GoZUWYhLsfyssNSQx4XUSJ7W+ygTpBgCA3oKDL5BMilGzHg28bIt60OpDEg4rGS88r2DLMsX4X4upyudo+xBYNRF6bYIYANFTGG1vAfePyg="
script: sh -x ./scripts/do-test.sh
after_success:
  - for f in `make -f tests/Makefile list_tests`;
    do
      cat tests/${f}.log;
    done
  - if [ "${CC}" = "gcc" ];
    then
      sh -x ./scripts/submit-coverage.sh ;
    fi
notifications:
  webhooks: https://coveralls.io/webhook

stages:
  - name: Build Documentation
    if: branch != master OR type != push
  - name: Build & Deploy Documentation
    if: branch = master AND type = push
  - name: Update Coverity Report
    if: branch = master AND type = push
jobs:
  include:
    - stage: Build Documentation
      name: Build Documentation
      script: sh -x ./scripts/do-docbuild.sh
      after_success:
    - stage: Build & Deploy Documentation
      name: Build Documentation and Deploy it to the rtpproxy.org repo
      script:
        - sh -x ./scripts/do-docbuild.sh
        - sh -x ./scripts/do-docdeploy.sh
      after_success:
    - stage: Update Coverity Report
      name: Push latest code to scan.coverity.com for analysis
      addons:
        coverity_scan:
          project:
            name: "sippy/rtpproxy"
            description: "A high-performance software proxy for RTP streams"
          notification_email: sobomax@sippysoft.com
          build_command_prepend: "./configure"
          build_command: "make all"
          branch_pattern: master
      before_install:
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      script:
        - true
      after_success:
