# force run: 1
os: linux
language: c
python:
  - "3.6"
before_install:
    - sh -x ./scripts/ft-before_install.sh
script: sh -x ./scripts/do-test.sh ${TTYPE}
after_success:
  - for f in `make -f tests/Makefile list_tests`;
    do
      cat tests/${f}.log;
    done

jobs:
  include:
    - name: "Glitching @ Ubuntu 16 GCC 7"
      dist: xenial
      compiler: gcc
      env:
        - TTYPE=glitching
