# force run: 1
dist: xenial
language: c
compiler:
#  - clang
  - gcc
python:
  - "3.6"
sudo: required
before_install:
    - sudo -H DEBIAN_FRONTEND=noninteractive apt-get update
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - which python
    - python --version
#    - sudo -H PATH="${PATH}:/usr/local/clang-3.4/bin" pip3 install -r requirements.txt
    - pip3 install --user cpp-coveralls
env:
  global:
    - COVERALLS_PARALLEL=true
script:
    sh -x ./scripts/do-test.sh
#after_success:
#  - for f in `make -f tests/Makefile list_tests`;
#    do
#      cat tests/${f}.log;
#    done
#  - if [ "${CC}" = "gcc" ];
#    then
#      sh -x ./scripts/submit-coverage.sh ;
#    fi
deploy:
  provider: releases
  file: docdeploy/${TRAVIS_BRANCH}/*.html
  file_glob: true
  overwrite: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  repo: sobomax/rtptestdoc
  release-number: v2.2
  tag_name: v2.2
  target_commitish: ${TRAVIS_COMMIT}
  prerelease: true
  on:
    branch: master
  on:
    branch: docdeploy

notifications:
  webhooks: https://coveralls.io/webhook
